export const PREVIEW_SAMPLES_2: Record<string, string> = {
  // Services
  "serviceName": "Premium Service Package",
  "serviceDescription": "Comprehensive solution including installation, maintenance, and support",
  "servicePrice": "$299",
  "service1": "Installation",
  "service2": "Repair",
  "service3": "Maintenance",
  "service4": "Consultation",
  "checklistTitle": "Everything You Need Included",
  "item1": "Free Initial Consultation",
  "item2": "Licensed & Insured Team",
  "item3": "Quality Materials Guaranteed",
  "item4": "Clean-Up After Every Job",
  "item5": "1-Year Warranty Included",
  "item6": "24/7 Customer Support",
  "areasTitle": "We Serve Your Area",
  "area1": "Downtown",
  "area2": "North Side",
  "area3": "West End",
  "area4": "East Valley",
  "area5": "South Hills",
  "area6": "Surrounding Counties",
  // Social Proof
  "customerCount": "5,000+",
  "reviewCount": "1,200+",
  "badge1Text": "Licensed & Insured",
  "badge2Text": "Secure Payment",
  "badge3Text": "5-Star Rated",
  "cert1": "State Licensed Contractor",
  "cert2": "BBB Accredited A+",
  "cert3": "EPA Certified",
  "cert4": "OSHA Compliant",
  "warrantyTitle": "Lifetime Warranty",
  "warrantyYears": "LIFETIME",
  "warrantyDetails": "All workmanship and materials covered for the lifetime of your ownership. We stand behind our work 100%.",
  "insuranceTitle": "Fully Insured & Bonded",
  "insuranceProvider": "State Farm Commercial",
  "insuranceDetails": "$2M liability coverage protects you and your property during every job.",
  // Comparison
  "option1Name": "Standard",
  "option1Price": "$149",
  "option1Feature1": "Basic features included",
  "option1Feature2": "Email support",
  "option2Name": "Professional",
  "option2Price": "$249",
  "option2Feature1": "All premium features",
  "option2Feature2": "Priority support",
  // Hero
  "heroHeadline": "Professional Service You Can Trust",
  "heroSubheadline": "Experience the difference with our certified experts and guaranteed satisfaction",
  "heroButtonText": "Schedule Today",
  // Features List
  "listHeading": "What's Included",
  "feature1": "Professional installation by certified technicians",
  "feature2": "Comprehensive warranty coverage",
  "feature3": "24/7 customer support",
  "feature4": "Satisfaction guarantee",
  "feature5": "Competitive pricing",
  // Contact
  "phone": "(555) 123-4567",
  "email": "info@example.com",
  "address": "123 Main St, Your City, ST 12345",
  "hours": "Mon-Fri: 8am-6pm, Sat: 9am-5pm",
  // Newsletter
  "newsletterHeading": "Stay Updated",
  "newsletterSubtext": "Get tips, special offers, and news delivered to your inbox",
  "buttonText": "Subscribe",
  // Video
  "videoTitle": "See Our Work in Action",
  "videoDescription": "Watch how we transform spaces and exceed expectations",
  // Before/After
  "beforeTitle": "Outdated & Worn",
  "beforeDescription": "Old materials, inefficient systems, and poor aesthetics affecting daily comfort",
  "afterTitle": "Modern & Efficient",
  "afterDescription": "Updated with quality materials, improved performance, and stunning visual appeal",
  // Project Timeline
  "phase1": "Planning & Design",
  "phase1Date": "Week 1-2",
  "phase2": "Material Procurement",
  "phase2Date": "Week 3",
  "phase3": "Installation",
  "phase3Date": "Week 4-6",
  "phase4": "Final Inspection",
  "phase4Date": "Week 7",
};
