export const PREVIEW_SAMPLES_1: Record<string, string> = {
  // Brand
  "brand.primaryColor": "#2563eb",
  // Features
  "feature1Title": "Fast & Reliable",
  "feature1Description": "Quick turnaround on all projects with 100% satisfaction guarantee",
  "feature2Title": "Expert Team",
  "feature2Description": "Certified professionals with years of experience",
  "feature3Title": "Affordable Pricing",
  "feature3Description": "Competitive rates without compromising quality",
  // Pricing
  "tier1Name": "Basic",
  "tier1Price": "$99",
  "tier1Features": "<li>Standard service</li><li>Email support</li><li>1-year warranty</li>",
  "tier2Name": "Premium",
  "tier2Price": "$199",
  "tier2Features": "<li>Priority service</li><li>24/7 support</li><li>Lifetime warranty</li>",
  // Testimonials
  "quote": "Best service I've ever received! Professional, timely, and exceeded expectations.",
  "customerName": "Sarah Johnson",
  "customerRole": "Homeowner",
  "reviewerName": "Michael Chen",
  "reviewText": "Outstanding quality and attention to detail. Would highly recommend!",
  "rating": "5.0",
  // CTA
  "ctaHeading": "Ready to Get Started?",
  "ctaSubtext": "Contact us today for a free consultation and quote",
  "ctaButtonText": "Get Your Free Quote",
  "urgencyHeading": "Limited Time Offer",
  "urgencySubtext": "Book this week and save 15%",
  "title": "24/7 Emergency Service Available",
  "subtext": "We're here when you need us most",
  "urgencyColor": "#dc2626",
  "heading": "Get Your Free Estimate Today",
  "amount": "$50 OFF",
  "code": "SAVE50",
  "expiry": "December 31, 2026",
  "stampText": "Limited Time",
  // Stats
  "stat1Number": "500+",
  "stat1Label": "Projects Completed",
  "stat2Number": "98%",
  "stat2Label": "Customer Satisfaction",
  "stat3Number": "15+",
  "stat3Label": "Years Experience",
  "stat4Number": "24/7",
  "stat4Label": "Support Available",
  // FAQ
  "question1": "What areas do you service?",
  "answer1": "We service the entire metro area and surrounding regions.",
  "question2": "Do you offer emergency services?",
  "answer2": "Yes, we provide 24/7 emergency service for urgent situations.",
  "question3": "What is your warranty policy?",
  "answer3": "All work comes with a comprehensive 1-year warranty.",
  // Process
  "step1Title": "Initial Consultation",
  "step1Description": "We discuss your needs and provide a detailed quote",
  "step2Title": "Schedule Service",
  "step2Description": "Pick a convenient time that works for you",
  "step3Title": "Complete Work",
  "step3Description": "Our team completes the job to perfection",
  "step4Title": "Follow-Up",
  "step4Description": "We ensure you're 100% satisfied with the results",
  // Content
  "leftHeading": "Our Approach",
  "leftDescription": "We combine expertise with personalized service to deliver exceptional results every time.",
  "rightHeading": "Your Benefits",
  "rightDescription": "Experience quality workmanship backed by our satisfaction guarantee and ongoing support.",
  // Guarantee
  "guaranteeHeadline": "100% Satisfaction Guaranteed",
  "guaranteeDescription": "If you're not completely satisfied, we'll make it right - no questions asked.",
  // Team
  "memberName": "John Smith",
  "memberRole": "Lead Technician",
  "memberBio": "Certified expert with 15+ years of experience delivering top-quality service.",
};
