import type { CoachingSuggestion, SalesStage } from '../types'

// Static coaching cards organized by stage
// These appear automatically when the rep enters a new stage
export const COACHING_CARDS: Record<SalesStage, CoachingSuggestion[]> = {
  greeting: [
    {
      id: 'greeting_intro',
      type: 'stage_prompt',
      title: 'Start Strong',
      body: 'Welcome them warmly and set expectations for the call. A strong opening builds trust from the first minute.',
      scriptText: 'Thanks so much for joining! I\'m [name] and I\'ll be walking you through everything today. This should take about 20-30 minutes — I\'ll learn about your situation, share how we can help, and answer any questions. Sound good?',
      stage: 'greeting',
      priority: 1,
      createdAt: 0,
      dismissed: false,
    },
  ],
  discovery: [
    {
      id: 'discovery_open',
      type: 'stage_prompt',
      title: 'Open-Ended Discovery',
      body: 'Ask broad questions first, then narrow down. Let them talk — the more they share, the better you can tailor your pitch.',
      scriptText: 'So tell me a little about what\'s going on — what prompted you to reach out to us today?',
      stage: 'discovery',
      priority: 1,
      createdAt: 0,
      dismissed: false,
    },
    {
      id: 'discovery_pain',
      type: 'info_alert',
      title: 'Listen for Pain Points',
      body: 'Pay attention to frustration, urgency, or failed attempts. These are your leverage points when presenting the solution.',
      stage: 'discovery',
      priority: 2,
      createdAt: 0,
      dismissed: false,
    },
  ],
  needs_assessment: [
    {
      id: 'needs_qualify',
      type: 'stage_prompt',
      title: 'Qualify the Scope',
      body: 'Get specific measurements and details. This shows professionalism and helps you give an accurate quote.',
      scriptText: 'To make sure I give you the most accurate quote, can you tell me about the size of the space? How many rooms or square feet are we looking at?',
      stage: 'needs_assessment',
      priority: 1,
      createdAt: 0,
      dismissed: false,
    },
  ],
  solution_presentation: [
    {
      id: 'solution_present',
      type: 'stage_prompt',
      title: 'Present Your Solution',
      body: 'Tie your solution directly to their pain points. Use their own words back to them.',
      scriptText: 'Based on what you\'ve described, here\'s what I\'d recommend. Our process starts with [step 1], then [step 2], and finishes with [step 3]. This addresses exactly the issues you mentioned about [their pain point].',
      stage: 'solution_presentation',
      priority: 1,
      createdAt: 0,
      dismissed: false,
    },
    {
      id: 'solution_diff',
      type: 'info_alert',
      title: 'Differentiate Early',
      body: 'Mention what makes you different BEFORE they ask about price. This anchors your value.',
      stage: 'solution_presentation',
      priority: 2,
      createdAt: 0,
      dismissed: false,
    },
  ],
  pricing_discussion: [
    {
      id: 'pricing_anchor',
      type: 'stage_prompt',
      title: 'Anchor the Value',
      body: 'Present the price confidently. Break down what\'s included so the number feels justified.',
      scriptText: 'For everything we discussed — [list key items] — the investment would be [price]. That includes [value items like warranty, follow-up, materials]. We can also discuss a deposit structure that works for you.',
      stage: 'pricing_discussion',
      priority: 1,
      createdAt: 0,
      dismissed: false,
    },
  ],
  objection_handling: [
    {
      id: 'objection_general',
      type: 'stage_prompt',
      title: 'Handle with Empathy',
      body: 'Never get defensive. Acknowledge their concern, ask clarifying questions, then reframe.',
      scriptText: 'That\'s a completely fair concern. Can you tell me more about what\'s holding you back? I want to make sure we find the right solution for you.',
      stage: 'objection_handling',
      priority: 1,
      createdAt: 0,
      dismissed: false,
    },
  ],
  closing: [
    {
      id: 'closing_assumptive',
      type: 'closing_script',
      title: 'Assumptive Close',
      body: 'Act as if the decision is made. Focus on logistics, not whether they want to proceed.',
      scriptText: 'Great, so let\'s get you on the schedule. What day works best for you — would next week be ideal, or would you prefer sooner?',
      stage: 'closing',
      priority: 1,
      createdAt: 0,
      dismissed: false,
    },
    {
      id: 'closing_urgency',
      type: 'closing_script',
      title: 'Create Urgency',
      body: 'Use real scarcity — your schedule, seasonal pricing, or limited availability.',
      scriptText: 'I should mention, our schedule is filling up quickly for [timeframe]. If we lock in your spot today, I can guarantee we\'ll have availability for you.',
      stage: 'closing',
      priority: 2,
      createdAt: 0,
      dismissed: false,
    },
  ],
  wrap_up: [
    {
      id: 'wrapup_confirm',
      type: 'stage_prompt',
      title: 'Confirm Next Steps',
      body: 'End with crystal-clear expectations. No ambiguity about what happens next.',
      scriptText: 'Perfect, let me summarize: [recap agreement]. I\'ll send over the estimate within the hour, and we have you tentatively scheduled for [date]. I\'ll follow up [timeframe] to confirm. Thanks again for your time!',
      stage: 'wrap_up',
      priority: 1,
      createdAt: 0,
      dismissed: false,
    },
  ],
}
