// Mock job data for development
import type { JobStatus } from "@/types";

export interface MockJob {
  id: string;
  companyId: string;
  customerId: string;
  customerName: string;
  title: string;
  description: string | null;
  status: JobStatus;
  scheduledDate: string;
  scheduledTime: string | null;
  estimatedDuration: number | null;
  address: string | null;
  assignedTo: string | null;
  notes: string | null;
  customFields: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export const mockJobs: MockJob[] = [
  {
    id: "1",
    companyId: "demo-tenant",
    customerId: "1",
    customerName: "John Smith",
    title: "Pool Cleaning",
    description: "Weekly pool maintenance and chemical balancing",
    status: "scheduled",
    scheduledDate: "2026-01-20",
    scheduledTime: "09:00",
    estimatedDuration: 60,
    address: "123 Main St, Austin, TX",
    assignedTo: "Mike Tech",
    notes: null,
    customFields: {},
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "2",
    companyId: "demo-tenant",
    customerId: "2",
    customerName: "Sarah Johnson",
    title: "Lawn Mowing",
    description: "Front and back yard mowing",
    status: "in_progress",
    scheduledDate: "2026-01-17",
    scheduledTime: "10:30",
    estimatedDuration: 45,
    address: "456 Oak Ave, Dallas, TX",
    assignedTo: "Jake Lawn",
    notes: "Customer prefers diagonal mowing pattern",
    customFields: {},
    createdAt: "2026-01-14T11:00:00Z",
    updatedAt: "2026-01-17T10:30:00Z",
  },
  {
    id: "3",
    companyId: "demo-tenant",
    customerId: "3",
    customerName: "Mike Williams",
    title: "HVAC Inspection",
    description: "Annual HVAC system inspection and filter replacement",
    status: "completed",
    scheduledDate: "2026-01-16",
    scheduledTime: "14:00",
    estimatedDuration: 90,
    address: "789 Pine Rd, Houston, TX",
    assignedTo: "Tom HVAC",
    notes: "Replaced filter, system running well",
    customFields: {},
    createdAt: "2026-01-10T09:00:00Z",
    updatedAt: "2026-01-16T15:30:00Z",
  },
  {
    id: "4",
    companyId: "demo-tenant",
    customerId: "4",
    customerName: "Emily Davis",
    title: "Pest Control Treatment",
    description: "Quarterly pest control spray",
    status: "scheduled",
    scheduledDate: "2026-01-21",
    scheduledTime: "11:00",
    estimatedDuration: 30,
    address: "321 Elm St, San Antonio, TX",
    assignedTo: "Pete Pest",
    notes: null,
    customFields: {},
    createdAt: "2026-01-12T14:00:00Z",
    updatedAt: "2026-01-12T14:00:00Z",
  },
  {
    id: "5",
    companyId: "demo-tenant",
    customerId: "5",
    customerName: "David Brown",
    title: "House Cleaning",
    description: "Deep cleaning - all rooms",
    status: "scheduled",
    scheduledDate: "2026-01-18",
    scheduledTime: "08:00",
    estimatedDuration: 180,
    address: "654 Maple Dr, Fort Worth, TX",
    assignedTo: "Clean Team",
    notes: "VIP customer - extra attention to detail",
    customFields: {},
    createdAt: "2026-01-13T08:00:00Z",
    updatedAt: "2026-01-13T08:00:00Z",
  },
  {
    id: "6",
    companyId: "demo-tenant",
    customerId: "6",
    customerName: "Lisa Anderson",
    title: "Plumbing Repair",
    description: "Fix leaky faucet in master bathroom",
    status: "completed",
    scheduledDate: "2026-01-15",
    scheduledTime: "13:00",
    estimatedDuration: 60,
    address: "987 Cedar Ln, El Paso, TX",
    assignedTo: "Phil Plumber",
    notes: "Replaced washer and tightened connection",
    customFields: {},
    createdAt: "2026-01-11T15:00:00Z",
    updatedAt: "2026-01-15T14:00:00Z",
  },
  {
    id: "7",
    companyId: "demo-tenant",
    customerId: "7",
    customerName: "Chris Martinez",
    title: "Window Cleaning",
    description: "Exterior window cleaning - 2 story home",
    status: "cancelled",
    scheduledDate: "2026-01-14",
    scheduledTime: "09:00",
    estimatedDuration: 120,
    address: "147 Birch Blvd, Arlington, TX",
    assignedTo: "Window Crew",
    notes: "Customer rescheduled due to weather",
    customFields: {},
    createdAt: "2026-01-08T10:00:00Z",
    updatedAt: "2026-01-13T16:00:00Z",
  },
  {
    id: "8",
    companyId: "demo-tenant",
    customerId: "1",
    customerName: "John Smith",
    title: "Pool Filter Replacement",
    description: "Replace pool pump filter",
    status: "scheduled",
    scheduledDate: "2026-01-22",
    scheduledTime: "10:00",
    estimatedDuration: 45,
    address: "123 Main St, Austin, TX",
    assignedTo: "Mike Tech",
    notes: null,
    customFields: {},
    createdAt: "2026-01-16T09:00:00Z",
    updatedAt: "2026-01-16T09:00:00Z",
  },
  {
    id: "9",
    companyId: "demo-tenant",
    customerId: "8",
    customerName: "Amanda Taylor",
    title: "Gutter Cleaning",
    description: "Clean gutters and check downspouts",
    status: "in_progress",
    scheduledDate: "2026-01-17",
    scheduledTime: "14:00",
    estimatedDuration: 90,
    address: "258 Spruce Way, Plano, TX",
    assignedTo: "Roof Team",
    notes: null,
    customFields: {},
    createdAt: "2026-01-14T12:00:00Z",
    updatedAt: "2026-01-17T14:00:00Z",
  },
  {
    id: "10",
    companyId: "demo-tenant",
    customerId: "9",
    customerName: "Robert Wilson",
    title: "Electrical Inspection",
    description: "Full home electrical safety inspection",
    status: "scheduled",
    scheduledDate: "2026-01-23",
    scheduledTime: "09:00",
    estimatedDuration: 120,
    address: "369 Willow Ct, Laredo, TX",
    assignedTo: "Elec Pro",
    notes: "Monthly service customer",
    customFields: {},
    createdAt: "2026-01-15T11:00:00Z",
    updatedAt: "2026-01-15T11:00:00Z",
  },
];
